// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: message.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TransmitterClient is the client API for Transmitter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransmitterClient interface {
	GetEntry(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Transmitter_GetEntryClient, error)
}

type transmitterClient struct {
	cc grpc.ClientConnInterface
}

func NewTransmitterClient(cc grpc.ClientConnInterface) TransmitterClient {
	return &transmitterClient{cc}
}

func (c *transmitterClient) GetEntry(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Transmitter_GetEntryClient, error) {
	stream, err := c.cc.NewStream(ctx, &Transmitter_ServiceDesc.Streams[0], "/transmitter.Transmitter/GetEntry", opts...)
	if err != nil {
		return nil, err
	}
	x := &transmitterGetEntryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Transmitter_GetEntryClient interface {
	Recv() (*Entry, error)
	grpc.ClientStream
}

type transmitterGetEntryClient struct {
	grpc.ClientStream
}

func (x *transmitterGetEntryClient) Recv() (*Entry, error) {
	m := new(Entry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TransmitterServer is the server API for Transmitter service.
// All implementations must embed UnimplementedTransmitterServer
// for forward compatibility
type TransmitterServer interface {
	GetEntry(*emptypb.Empty, Transmitter_GetEntryServer) error
	mustEmbedUnimplementedTransmitterServer()
}

// UnimplementedTransmitterServer must be embedded to have forward compatible implementations.
type UnimplementedTransmitterServer struct {
}

func (UnimplementedTransmitterServer) GetEntry(*emptypb.Empty, Transmitter_GetEntryServer) error {
	return status.Errorf(codes.Unimplemented, "method GetEntry not implemented")
}
func (UnimplementedTransmitterServer) mustEmbedUnimplementedTransmitterServer() {}

// UnsafeTransmitterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransmitterServer will
// result in compilation errors.
type UnsafeTransmitterServer interface {
	mustEmbedUnimplementedTransmitterServer()
}

func RegisterTransmitterServer(s grpc.ServiceRegistrar, srv TransmitterServer) {
	s.RegisterService(&Transmitter_ServiceDesc, srv)
}

func _Transmitter_GetEntry_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TransmitterServer).GetEntry(m, &transmitterGetEntryServer{stream})
}

type Transmitter_GetEntryServer interface {
	Send(*Entry) error
	grpc.ServerStream
}

type transmitterGetEntryServer struct {
	grpc.ServerStream
}

func (x *transmitterGetEntryServer) Send(m *Entry) error {
	return x.ServerStream.SendMsg(m)
}

// Transmitter_ServiceDesc is the grpc.ServiceDesc for Transmitter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Transmitter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transmitter.Transmitter",
	HandlerType: (*TransmitterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEntry",
			Handler:       _Transmitter_GetEntry_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "message.proto",
}
